name: build-tables

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 16 * * SUN"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout website repo
        uses: actions/checkout@v2
        with:
          path: main
      
      - name: Checkout builder repo
        uses: actions/checkout@v2
        with:
          repository: NotMichaelChen/stellatablebuilder
          path: builder
          
      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v1.3.51
        with:
          nim-version: 1.6.6
      
      - name: Build tables
        run: |
          cd builder
          nimble run -d:release -y -- --outputPath ../main/data/
          cd ../main
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update table data"
          git push
