# This is a basic workflow to help you get started with Actions

name: build-tables

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout website repo
        uses: actions/checkout@v2
        with:
          path: main
      
      - name: Checkout builder repo
        uses: actions/checkout@v2
        with:
          repository: NotMichaelChen/stellatablebuilder
          path: builder
          
      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v1.1.4
        with:
          nim-version: 1.4.8
      
      - name: Build tables
        run: |
          cd builder
          nimble build -y
          ./bin/stellatablebuilder ../main/data/
          cd ../main
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update table data"
          git push
